# This is a basic workflow to help you get started with Actions

name: Windows Full Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set the build type here
env:
  CI_ENV_BUILD_TYPE: Release
  B_BUILD_DIR: build
  B_BUILD_TYPE: Release
  INPUTLEAP_VERSION_STAGE: Release
  DEBIAN_FRONTEND: noninteractive

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  win-build-2022:
    runs-on: windows-2022

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Download Bonjour SDK-like
        run: ./azure-pipelines/download_install_bonjour_sdk_like.ps1
      - name: Installing QT
        run: ./azure-pipelines/download_install_qt.ps1
      - name: Get build env
        run: Copy-Item azure-pipelines\build_env_tmpl.bat build_env.bat
      - name: Build
        run: call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64 && clean_build.bat
        shell: cmd
      - uses: papeloto/action-zip@v1
        with:
          files: build\bin\${{ env.CI_ENV_BUILD_TYPE }}
          dest: ${{ env.CI_ENV_BUILD_TYPE }}.zip
        name: Archive Completed Build Directory
      - uses: actions/upload-artifact@v3
        with:
          name: Windows-2022-${{ env.CI_ENV_BUILD_TYPE }}
          path: ${{ env.CI_ENV_BUILD_TYPE }}.zip
      - name: Build the Installer
        run: .\build_installer.bat
        if: ${{ env.CI_ENV_BUILD_TYPE == 'Release' }}
        shell: cmd
      - uses: actions/upload-artifact@v3
        if: ${{ env.CI_ENV_BUILD_TYPE == 'Release' }}
        with:
          name: Publish the Installer
          path: .\build\installer-inno\bin
          if-no-files-found: warn
